/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/3D/vape3d.glb 
Author: C01L3D (https://sketchfab.com/c01l3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smoant-charon-baby-8cc0440ce9414881ac9dd2b2280d415a
Title: Smoant Charon Baby
*/

import React, { Suspense, useRef } from "react";
import {
  useGLTF,
  useAnimations,
  OrbitControls,
  Decal,
  useTexture,
} from "@react-three/drei";
import { easing } from "maath";
import { useSnapshot } from "valtio";
import { useFrame, useThree } from "@react-three/fiber";
import state from "../storeProxy";

import { MeshBasicMaterial } from "three";
import { useLoader } from "@react-three/fiber";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/3D/vape3d.glb");
  const { actions } = useAnimations(animations, group);
  const snap = useSnapshot(state);

  const logoTexture = useTexture(snap.logoDecal);
  const fullTexture = useTexture(snap.fullDecal);

  console.log("VAPE", materials);

  const logoMaterial = new MeshBasicMaterial({ map: logoTexture });

  useFrame((state, delta) =>
    easing.dampC(materials.LabelMat.color, snap.color, 0.25, delta)
  );

  const stateString = JSON.stringify(snap);

  return (
    <group ref={group} {...props} dispose={null} key={stateString}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="charonbabyfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Cartridge"
                  position={[370, 1500, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[440, 200, 570]}
                >
                  <mesh
                    name="Cartridge_CartridgeMat_0"
                    geometry={nodes.Cartridge_CartridgeMat_0.geometry}
                    material={logoMaterial}
                  />
                </group>
                <group
                  name="Case"
                  position={[0, -340, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[1260, 480, 1750]}
                >
                  <mesh
                    name="Case_LabelMat_0"
                    geometry={nodes.Case_LabelMat_0.geometry}
                    material={logoMaterial}
                  />
                  <mesh
                    name="Case_PodMat_0"
                    geometry={nodes.Case_PodMat_0.geometry}
                    material={logoMaterial}
                    material-color={snap.color}
                  />
                  <mesh
                    name="Case_CartridgeMat_0"
                    geometry={nodes.Case_CartridgeMat_0.geometry}
                    material={materials.CartridgeMat}
                  />
                  <mesh
                    name="Case_IndicatorMat_0"
                    geometry={nodes.Case_IndicatorMat_0.geometry}
                    material={materials.IndicatorMat}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3D/vape3d.glb");
