export const CREATE_CHATS_REQUEST = "CREATE_CHATS_REQUEST";
export const CREATE_CHATS_SUCCESS = "CREATE_CHATS_SUCCESS";
export const CREATE_CHATS_FAIL = "CREATE_CHATS_FAIL";
export const CREATE_CHATS_RESET = "CREATE_CHATS_RESET";

export const GET_CHAT_REQUEST = "GET_CHAT_REQUEST";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAIL = "GET_CHAT_FAIL";

export const GET_FINDCHAT_REQUEST = "GET_FINDCHAT_REQUEST";
export const GET_FINDCHAT_SUCCESS = "GET_FINDCHAT_SUCCESS";
export const GET_FINDCHAT_FAIL = "GET_FINDCHAT_FAIL";

export const GET_USER_CHATS_REQUEST = "GET_USER_CHATS_REQUEST";
export const GET_USER_CHATS_SUCCESS = "GET_USER_CHATS_SUCCESS";
export const GET_USER_CHATS_FAIL = "GET_USER_CHATS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
