export const CREATE_MESSAGES_REQUEST = "CREATE_MESSAGES_REQUEST";
export const CREATE_MESSAGES_SUCCESS = "CREATE_MESSAGES_SUCCESS";
export const CREATE_MESSAGES_FAIL = "CREATE_MESSAGES_FAIL";
export const CREATE_MESSAGES_RESET = "CREATE_MESSAGES_RESET";

export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
