export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// For Sorted the Products
// export const PRODUCT_SORT_REQUEST = 'PRODUCT_SORT_REQUEST';
// export const PRODUCT_SORT_SUCCESS  = 'PRODUCT_SORT_REQUEST';
// export const PRODUCT_SORT_FAIL = 'PRODUCT_SORT_REQUEST';
