export const GET_TERMS_REQUEST = "GET_TERMS_REQUEST";
export const GET_TERMS_SUCCESS = "GET_TERMS_SUCCESS";
export const GET_TERMS_FAIL = "GET_TERMS_FAIL";

export const CREATE_TERMS_REQUEST = "CREATE_TERMS_REQUEST";
export const CREATE_TERMS_SUCCESS = "CREATE_TERMS_SUCCESS";
export const CREATE_TERMS_FAIL = "CREATE_TERMS_FAIL";
export const CREATE_TERMS_RESET = "CREATE_TERMS_RESET";

export const UPDATE_TERMS_REQUEST = "UPDATE_TERMS_REQUEST";
export const UPDATE_TERMS_SUCCESS = "UPDATE_TERMS_SUCCESS";
export const UPDATE_TERMS_FAIL = "UPDATE_TERMS_FAIL";
export const UPDATE_TERMS_RESET = "UPDATE_TERMS_RESET";

export const DELETE_TERMS_REQUEST = "DELETE_TERMS_REQUEST";
export const DELETE_TERMS_SUCCESS = "DELETE_TERMS_SUCCESS";
export const DELETE_TERMS_FAIL = "DELETE_TERMS_FAIL";
export const DELETE_TERMS_RESET = "DELETE_TERMS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
